import React, { useEffect, useMemo, useState } from 'react';
import { ShieldCheck, LayoutDashboard, Boxes, Truck, ClipboardList, Wrench, FileDown, LogOut, Search, Plus, RefreshCw, AlertTriangle, Menu, X, Activity } from 'lucide-react';
import Chatbot from "./Chatbot";
const API = (import.meta.env.VITE_API_URL || 'http://localhost:5000/api').replace(/\/$/, '');
const getToken = () => sessionStorage.getItem('gc_token') || '';
async function api(path, options={}) {
  const headers = { ...(options.body ? {'Content-Type':'application/json'} : {}), ...(options.headers||{}), ...(getToken() ? {Authorization:`Bearer ${getToken()}`} : {}) };
  const response = await fetch(`${API}${path}`, {...options, headers});
  if (!response.ok) {
    const data = await response.json().catch(()=>({}));
    throw new Error(data.error || `Request failed (${response.status})`);
  }
  if (response.headers.get('content-type')?.includes('text/csv')) return response.blob();
  return response.status === 204 ? null : response.json();
}
const moneyless = n => Number(n || 0).toLocaleString();
const initialForm = {name:'',category:'General Supplies',quantity:0,min_stock:5,unit:'units',condition_status:'Available',location_label:'Demo Store A'};
const navItems = [
  ['Dashboard',LayoutDashboard],['Inventory',Boxes],['Suppliers',Truck],
  ['Allocations',ClipboardList],['Maintenance',Wrench],['Transactions',Activity]
];

function Login({onLogin}) {
  const [email,setEmail]=useState('admin@guardian.local'), [password,setPassword]=useState('DemoPass123!'), [error,setError]=useState(''), [busy,setBusy]=useState(false);
  async function submit(e) { e.preventDefault(); setError(''); setBusy(true); try { const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})}); sessionStorage.setItem('gc_token',d.token); onLogin(d.user); } catch(err){setError(err.message)} finally{setBusy(false)} }
  return <div className="login-wrap"><form className="login-card" onSubmit={submit}><div className="brand-mark"><ShieldCheck size={30}/></div><p className="eyebrow">GUARDIANCORE · ACADEMIC DEMO</p><h1>Welcome back</h1><p className="muted">Sign in to the inventory workspace.</p>{error&&<div className="alert error">{error}</div>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary full" disabled={busy}>{busy?'Signing in…':'Sign in securely'}</button><p className="hint">Demo: admin@guardian.local / DemoPass123!</p></form></div>;
}

export default function App() {
  const [user,setUser]=useState(null), [page,setPage]=useState('Dashboard'), [summary,setSummary]=useState({}), [categories,setCategories]=useState([]), [recent,setRecent]=useState([]), [items,setItems]=useState([]), [rows,setRows]=useState([]), [q,setQ]=useState(''), [error,setError]=useState(''), [notice,setNotice]=useState(''), [modal,setModal]=useState(false), [edit,setEdit]=useState(null), [busy,setBusy]=useState(false), [mobileNav,setMobileNav]=useState(false);
  const [form,setForm]=useState(initialForm), [stock,setStock]=useState({}), [supplier,setSupplier]=useState({name:'',contact:'',email:'',address:''}), [allocation,setAllocation]=useState({item_id:'',unit_label:'Demo Unit',quantity:1,allocation_date:new Date().toISOString().slice(0,10),note:''}), [maint,setMaint]=useState({item_id:'',maintenance_type:'Routine inspection',due_date:'',status:'Scheduled',note:''});
  const canEdit=['Admin','Store Officer'].includes(user?.role), isAdmin=user?.role==='Admin';
  function fail(err){setError(err.message);setNotice('');}
  function success(msg){setNotice(msg);setError('');}
  async function load() {
    setError('');
    try {
      if(page==='Dashboard') { const d=await api('/dashboard'); setSummary(d.summary||{});setCategories(d.categories||[]);setRecent(d.recent||[]); }
      if(page==='Inventory') setItems(await api(`/inventory?q=${encodeURIComponent(q)}`));
      if(page==='Transactions') setRows(await api('/transactions'));
      if(page==='Suppliers') setRows(await api('/suppliers'));
      if(page==='Allocations') {setItems(await api('/inventory'));setRows(await api('/allocations'));}
      if(page==='Maintenance') {setItems(await api('/inventory'));setRows(await api('/maintenance'));}
    } catch(e){fail(e)}
  }
  useEffect(()=>{if(user) load();},[user,page]);
  useEffect(()=>{if(user&&page==='Inventory'){const t=setTimeout(()=>api(`/inventory?q=${encodeURIComponent(q)}`).then(setItems).catch(fail),250);return()=>clearTimeout(t)}},[q,user,page]);
  function logout(){sessionStorage.removeItem('gc_token');setUser(null);setPage('Dashboard');}
  async function saveItem(e) {
    e.preventDefault();setBusy(true);
    try { if(edit) await api(`/inventory/${edit.id}`,{method:'PUT',body:JSON.stringify({...form,quantity:undefined})}); else await api('/inventory',{method:'POST',body:JSON.stringify(form)});
      setModal(false);setEdit(null);setForm(initialForm);success(edit?'Inventory updated.':'Inventory item added.');await load();
    } catch(e){fail(e)} finally{setBusy(false)}
  }
  async function removeItem(item) { if(!confirm(`Delete ${item.name}?`))return;try{await api(`/inventory/${item.id}`,{method:'DELETE'});success('Inventory item deleted.');await load()}catch(e){fail(e)}}
  async function moveStock(item,type) {
    const s=stock[item.id]||{}; if(!Number(s.quantity)||Number(s.quantity)<1){fail(new Error('Enter a positive quantity.'));return}
    try{await api(`/inventory/${item.id}/stock`,{method:'POST',body:JSON.stringify({type,quantity:Number(s.quantity),note:s.note||''})});setStock({...stock,[item.id]:{quantity:'',note:''}});success(`Stock ${type.toLowerCase()} successfully.`);await load()}catch(e){fail(e)}
  }
  async function addSupplier(e){e.preventDefault();try{await api('/suppliers',{method:'POST',body:JSON.stringify(supplier)});setSupplier({name:'',contact:'',email:'',address:''});success('Supplier added.');await load()}catch(e){fail(e)}}
  async function addAllocation(e){e.preventDefault();try{await api('/allocations',{method:'POST',body:JSON.stringify({...allocation, item_id:Number(allocation.item_id),quantity:Number(allocation.quantity)})});success('Allocation recorded and stock reduced.');await load()}catch(e){fail(e)}}
  async function addMaintenance(e){e.preventDefault();try{await api('/maintenance',{method:'POST',body:JSON.stringify({...maint,item_id:Number(maint.item_id),due_date:maint.due_date||null})});success('Maintenance record added.');await load()}catch(e){fail(e)}}
  async function exportCsv(){try{const blob=await api('/reports/inventory.csv');const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='inventory-report.csv';a.click();URL.revokeObjectURL(url)}catch(e){fail(e)}}
  const title=page;
  if(!user)return <Login onLogin={setUser}/>;
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav?'open':''}`}><div className="logo"><div className="logo-icon"><ShieldCheck/></div><div><b>GuardianCore</b><small>INVENTORY SYSTEM</small></div><button className="mobile-close ghost" onClick={()=>setMobileNav(false)}><X/></button></div><div className="workspace-label">WORKSPACE</div>{navItems.map(([name,Icon])=><button key={name} className={`nav-link ${page===name?'active':''}`} onClick={()=>{setPage(name);setMobileNav(false);setError('');setNotice('')}}><Icon size={18}/>{name}</button>)}<div className="sidebar-bottom"><div className="secure-tag"><ShieldCheck size={16}/> Academic demo environment</div><div className="profile"><div className="avatar">{user.name?.[0]||'U'}</div><div className="profile-info"><b>{user.name}</b><small>{user.role}</small></div><button className="ghost logout" title="Sign out" onClick={logout}><LogOut size={17}/></button></div></div></aside>
    {mobileNav&&<div className="scrim" onClick={()=>setMobileNav(false)}/>}
    <main className="main-area"><header className="topbar"><button className="mobile-menu ghost" onClick={()=>setMobileNav(true)}><Menu/></button><div><p className="eyebrow">NATIONAL DEFENCE · INVENTORY</p><h1>{title}</h1></div><div className="top-actions"><span className="status-pill"><span/> Demo environment</span><button className="icon-button" title="Refresh" onClick={load}><RefreshCw size={17}/></button></div></header>
      <div className="content">
        {error&&<div className="alert error"><AlertTriangle size={18}/>{error}<button className="ghost" onClick={()=>setError('')}>×</button></div>}
        {notice&&<div className="alert success">{notice}<button className="ghost" onClick={()=>setNotice('')}>×</button></div>}
        {page==='Dashboard'&&<Dashboard summary={summary} categories={categories} recent={recent} onNavigate={setPage}/>}
        {page==='Inventory'&&<><div className="page-tools"><div className="search"><Search size={17}/><input placeholder="Search inventory or category…" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="tool-buttons"><button className="secondary" onClick={exportCsv}><FileDown size={16}/> Export CSV</button>{canEdit&&<button className="primary" onClick={()=>{setEdit(null);setForm(initialForm);setModal(true)}}><Plus size={17}/> Add item</button>}</div></div><div className="table-card"><div className="table-head"><div><h2>Inventory register</h2><p>{items.length} records · fictional sample supplies</p></div></div><InventoryTable items={items} canEdit={canEdit} isAdmin={isAdmin} stock={stock} setStock={setStock} onMove={moveStock} onEdit={item=>{setEdit(item);setForm({...item});setModal(true)}} onDelete={removeItem}/></div></>}
        {page==='Suppliers'&&<><form className="inline-form panel" onSubmit={addSupplier}><h2>Add supplier</h2><div className="form-grid"><Field label="Supplier name" value={supplier.name} set={v=>setSupplier({...supplier,name:v})} required/><Field label="Contact" value={supplier.contact} set={v=>setSupplier({...supplier,contact:v})}/><Field label="Email" type="email" value={supplier.email} set={v=>setSupplier({...supplier,email:v})}/><Field label="Address" value={supplier.address} set={v=>setSupplier({...supplier,address:v})}/></div><button className="primary">Save supplier</button></form><DataTable title="Suppliers" rows={rows} columns={[['name','Supplier'],['contact','Contact'],['email','Email'],['address','Address']]}/></>}
        {page==='Allocations'&&<><form className="inline-form panel" onSubmit={addAllocation}><h2>Record allocation</h2><p className="muted">Allocation reduces available stock and records an issue transaction.</p><div className="form-grid"><label>Item<select required value={allocation.item_id} onChange={e=>setAllocation({...allocation,item_id:e.target.value})}><option value="">Select item</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} ({i.quantity} available)</option>)}</select></label><Field label="Unit label" value={allocation.unit_label} set={v=>setAllocation({...allocation,unit_label:v})} required/><Field label="Quantity" type="number" min="1" value={allocation.quantity} set={v=>setAllocation({...allocation,quantity:v})} required/><Field label="Allocation date" type="date" value={allocation.allocation_date} set={v=>setAllocation({...allocation,allocation_date:v})} required/><Field label="Note" value={allocation.note} set={v=>setAllocation({...allocation,note:v})}/></div><button className="primary">Save allocation</button></form><DataTable title="Allocation register" rows={rows} columns={[['item_name','Item'],['unit_label','Unit'],['quantity','Quantity'],['allocation_date','Date'],['status','Status'],['note','Note']]}/></>}
        {page==='Maintenance'&&<><form className="inline-form panel" onSubmit={addMaintenance}><h2>Schedule maintenance</h2><div className="form-grid"><label>Item<select required value={maint.item_id} onChange={e=>setMaint({...maint,item_id:e.target.value})}><option value="">Select item</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><Field label="Maintenance type" value={maint.maintenance_type} set={v=>setMaint({...maint,maintenance_type:v})} required/><Field label="Due date" type="date" value={maint.due_date} set={v=>setMaint({...maint,due_date:v})}/><label>Status<select value={maint.status} onChange={e=>setMaint({...maint,status:e.target.value})}><option>Scheduled</option><option>In Progress</option><option>Completed</option></select></label><Field label="Note" value={maint.note} set={v=>setMaint({...maint,note:v})}/></div><button className="primary">Save maintenance</button></form><DataTable title="Maintenance register" rows={rows} columns={[['item_name','Item'],['maintenance_type','Type'],['due_date','Due date'],['status','Status'],['note','Note']]}/></>}
        {page==='Transactions'&&<DataTable title="Transaction history" rows={rows} columns={[['createdAt','Date'],['itemName','Item'],['type','Action'],['quantity','Quantity'],['userName','Recorded by'],['note','Note']]}/>}
        <footer>GuardianCore · Academic mini-project · Use fictional demonstration data only.</footer>
      </div>
    </main>
    <Chatbot />
    {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><form className="modal" onSubmit={saveItem}><div className="modal-title"><div><p className="eyebrow">INVENTORY REGISTER</p><h2>{edit?'Edit item':'Add inventory item'}</h2></div><button type="button" className="ghost" onClick={()=>setModal(false)}><X/></button></div><div className="form-grid"><Field label="Item name" value={form.name} set={v=>setForm({...form,name:v})} required/><Field label="Category" value={form.category} set={v=>setForm({...form,category:v})} required/>{!edit&&<Field label="Opening quantity" type="number" min="0" value={form.quantity} set={v=>setForm({...form,quantity:v})} required/>}<Field label="Minimum stock" type="number" min="0" value={form.min_stock} set={v=>setForm({...form,min_stock:v})} required/><Field label="Unit" value={form.unit} set={v=>setForm({...form,unit:v})}/><label>Condition<select value={form.condition_status} onChange={e=>setForm({...form,condition_status:e.target.value})}><option>Available</option><option>Damaged</option><option>Under Maintenance</option></select></label><Field label="Store label" value={form.location_label} set={v=>setForm({...form,location_label:v})}/></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(false)}>Cancel</button><button className="primary" disabled={busy}>{busy?'Saving…':'Save item'}</button></div></form></div>}
  </div>;
}

function Field({label,value,set,type='text',required=false,min}) { return <label>{label}<input type={type} min={min} value={value??''} onChange={e=>set(e.target.value)} required={required}/></label> }
function Dashboard({summary,categories,recent,onNavigate}) {
  const cards=[['Inventory records',summary.totalItems,Boxes,'blue'],['Total units',summary.totalUnits,Activity,'green'],['Low-stock items',summary.lowStock,AlertTriangle,'amber'],['Under maintenance',summary.underMaintenance,Wrench,'purple']];
  return <><div className="welcome"><div><p className="eyebrow">OVERVIEW</p><h2>Inventory at a glance</h2><p>Monitor demo inventory records, stock levels and recent movements.</p></div><button className="secondary" onClick={()=>onNavigate('Inventory')}>View inventory <Boxes size={16}/></button></div><div className="metric-grid">{cards.map(([label,value,Icon,color])=><div className="metric" key={label}><div className={`metric-icon ${color}`}><Icon size={19}/></div><p>{label}</p><strong>{moneyless(value)}</strong><small>Current database summary</small></div>)}</div><div className="dashboard-grid"><section className="panel"><div className="section-heading"><div><h2>Category overview</h2><p>Current quantity by supply category</p></div></div>{categories.length?categories.map(c=><div className="category-row" key={c.category}><div className="category-top"><b>{c.category}</b><span>{moneyless(c.units)} units</span></div><div className="bar"><span style={{width:`${Math.max(3,Math.min(100,Number(c.units)/(Math.max(1,...categories.map(x=>Number(x.units))))*100))}%`}}/></div><small>{c.itemCount} inventory records</small></div>):<Empty/>}</section><section className="panel"><div className="section-heading"><div><h2>Recent movements</h2><p>Latest stock transactions</p></div><button className="text-button" onClick={()=>onNavigate('Transactions')}>View all</button></div>{recent.length?recent.map(t=><div className="movement" key={t.id}><div className={`movement-icon ${t.type==='Received'?'green':'amber'}`}>{t.type==='Received'?'+':'−'}</div><div className="movement-info"><b>{t.itemName}</b><small>{new Date(t.createdAt).toLocaleString()}</small></div><span className={t.type==='Received'?'positive':'negative'}>{t.type==='Received'?'+':'−'}{t.quantity}</span></div>):<Empty/>}</section></div><div className="demo-note"><ShieldCheck size={18}/><div><b>Academic demonstration mode</b><p>All sample records represent ordinary supplies. No real or operational defence information should be entered.</p></div></div></>;
}
function InventoryTable({items,canEdit,isAdmin,stock,setStock,onMove,onEdit,onDelete}) {
  if(!items.length)return <Empty/>;
  return <div className="table-scroll"><table><thead><tr><th>Item</th><th>Category</th><th>Stock</th><th>Condition</th><th>Stock movement</th><th>Actions</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><b>{i.name}</b><small className="subcell">{i.location_label} · ID {i.id}</small></td><td>{i.category}</td><td><b>{moneyless(i.quantity)} {i.unit}</b><small className={`subcell ${i.quantity<=i.min_stock?'low':''}`}>{i.quantity<=i.min_stock?'Low stock':'In stock'} · minimum {i.min_stock}</small></td><td><span className={`pill ${i.condition_status==='Available'?'good':i.condition_status==='Damaged'?'bad':'warn'}`}>{i.condition_status}</span></td><td>{canEdit?<div className="stock-editor"><input aria-label="Quantity" type="number" min="1" placeholder="Qty" value={stock[i.id]?.quantity??''} onChange={e=>setStock({...stock,[i.id]:{...stock[i.id],quantity:e.target.value}})}/><input aria-label="Note" placeholder="Note" value={stock[i.id]?.note??''} onChange={e=>setStock({...stock,[i.id]:{...stock[i.id],note:e.target.value}})}/><button className="tiny green-btn" onClick={()=>onMove(i,'Received')}>Receive</button><button className="tiny amber-btn" onClick={()=>onMove(i,'Issued')}>Issue</button></div>:<span className="muted">Read only</span>}</td><td><div className="row-actions">{canEdit&&<button className="text-button" onClick={()=>onEdit(i)}>Edit</button>}{isAdmin&&<button className="text-button danger-text" onClick={()=>onDelete(i)}>Delete</button>}</div></td></tr>)}</tbody></table></div>;
}
function DataTable({title,rows,columns}) { return <section className="panel table-card"><div className="table-head"><h2>{title}</h2><span className="muted">{rows.length} records</span></div>{rows.length?<div className="table-scroll"><table><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{columns.map(([key])=><td key={key}>{r[key]===null||r[key]===''||r[key]===undefined?'—':String(r[key])}</td>)}</tr>)}</tbody></table></div>:<Empty/>}</section> }
function Empty(){return <div className="empty"><Boxes size={25}/><b>No records yet</b><span>Records will appear here when available.</span></div>}